/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.menu.MenuAdd;
import view.menu.MenuList;
import view.meja.TableAdd;
import view.meja.TableList;
import view.kategori.KategoriAdd;
import view.kategori.KategoriList;

/**
 *
 * @author ekky
 */
public class MainAdmin extends javax.swing.JFrame {

    
    /**
     * Creates new form Main
     */
    public MainAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputEdit = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        meja = new javax.swing.JMenuItem();
        menuMakanan = new javax.swing.JMenuItem();
        kategori = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Retoran");
        setSize(new java.awt.Dimension(300, 300));
        getContentPane().setLayout(new java.awt.GridLayout());

        jLabel1.setText("Selamat datang admin");
        inputEdit.add(jLabel1);

        getContentPane().add(inputEdit);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(200, 21));

        jMenu1.setText("File");

        meja.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        meja.setText("Meja");
        meja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mejaActionPerformed(evt);
            }
        });
        jMenu1.add(meja);

        menuMakanan.setText("Makanan & Minuman");
        menuMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMakananActionPerformed(evt);
            }
        });
        jMenu1.add(menuMakanan);

        kategori.setText("Kategori");
        kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoriActionPerformed(evt);
            }
        });
        jMenu1.add(kategori);

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu1.add(logout);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mejaActionPerformed
        // TODO add your handling code here:
        inputEdit.removeAll();
        inputEdit.repaint();
        inputEdit.revalidate();
        TableList content = new TableList();
        content.setSize(inputEdit.getWidth(),inputEdit.getHeight());
        content.setVisible(true);
        inputEdit.add(content);
       
        
    }//GEN-LAST:event_mejaActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void menuMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMakananActionPerformed
        // TODO add your handling code here:
       
        
        inputEdit.removeAll();
        inputEdit.repaint();
        MenuAdd form = new MenuAdd();
        form.setSize(inputEdit.getWidth(),inputEdit.getHeight());
        form.setVisible(true);
        
        inputEdit.add(form);
    }//GEN-LAST:event_menuMakananActionPerformed

    private void kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriActionPerformed
        // TODO add your handling code here:
       
        
        inputEdit.removeAll();
        inputEdit.repaint();
        KategoriAdd form = new KategoriAdd();
        form.setSize(inputEdit.getWidth(),inputEdit.getHeight());
        form.setVisible(true);
        
        inputEdit.add(form);
    }//GEN-LAST:event_kategoriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                System.out.println(info.getName());
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel inputEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem kategori;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenuItem meja;
    private javax.swing.JMenuItem menuMakanan;
    // End of variables declaration//GEN-END:variables
}
