/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.menu;

/**
 *
 * @author ekky
 */
public class MenuList extends javax.swing.JPanel {

    /**
     * Creates new form MenuList
     */
    public MenuList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"mn001", "Ceker Setan", "Makanan", "Makanan Pembuka", "-", "Edit | Hapus"},
                {"mn002", "Jamur Goreng Garing", "Makanan", "Makanan Pembuka", "-", "Edit | Hapus"},
                {"mn003", "Ayam Penyet", "Makanan", "Makanan Utama", "-", "Edit | Hapus"},
                {"mn004", "Cumi Asam Manis", "Makanan", "Makanan Utama", "-", "Edit | Hapus"},
                {"mn005", "Pisang Keju", "Makanan", "Makanan Penutup", "-", "Edit | Hapus"},
                {"mn006", "Singkong Keju", "Makanan", "Makanan Penutup", "-", "Edit | Hapus"},
                {"mn007", "Kopi Hitam", "Minuman", "Kopi", "-", "Edit | Hapus"},
                {"mn008", "Kopi Susu", "Minuman", "Kopi", "-", "Edit | Hapus"},
                {"mn009", "Teh Tarik", "Minuman", "Teh", "-", "Edit | Hapus"},
                {"mn010", "Teh Hijau", "Minuman", "Teh", "-", "Edit | Hapus"},
                {"mn011", "Susu Soda", "Minuman", "Soda", "-", "Edit | Hapus"},
                {"mn012", "Sprite", "Minuman", "Soda", "-", "Edit | Hapus"},
                {"mn013", "Milkshake Coklat", "Minuman", "Milkshake", "-", "Edit | Hapus"},
                {"mn014", "Milkshake Apel", "Minuman", "MIlkshake", "-", "Edit | Hapus"}
            },
            new String [] {
                "No Menu", "Nama Menu", "Jenis", "Kategori", "Gambar", "Aksi"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Tambah Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
